# Generated by Django 4.2.2 on 2023-12-04 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_check_in', models.DateField()),
                ('reservation_check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.FloatField()),
                ('review_comment', models.TextField()),
                ('review_created_at', models.DateTimeField(auto_now_add=True)),
                ('review_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_address_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('room_address_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('room_des', models.TextField()),
                ('room_capacity', models.IntegerField()),
                ('room_created_at', models.DateTimeField(auto_now_add=True)),
                ('room_updated_at', models.DateTimeField(auto_now=True)),
                ('room_reservation', models.ManyToManyField(blank=True, related_name='user_room', through='rooms.Reservation', to=settings.AUTH_USER_MODEL)),
                ('room_review', models.ManyToManyField(blank=True, related_name='review_room', through='rooms.Review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='review_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviewed', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservated', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
