# Generated by Django 4.2.2 on 2023-12-05 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='room_host',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.host'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
