# Generated by Django 4.2.2 on 2023-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_image',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
