# Generated by Django 4.2.2 on 2023-12-05 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_remove_category_room_alter_room_room_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_image',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='room_image',
            old_name='room',
            new_name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='room_address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_daily_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_reservation',
            field=models.ManyToManyField(null=True, related_name='user_room', through='rooms.Reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_review',
            field=models.ManyToManyField(null=True, related_name='review_room', through='rooms.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
